#!/usr/bin/env sh
set -eu

################################################################################
# Ensure shell scripts conform to shellcheck.
################################################################################

readonly DEBUG="${DEBUG:-unset}"
if [ "${DEBUG}" != unset ]; then
  set -x
fi

detect-secrets-hook --base64-limit 4.5 --hex-limit 3
